### PR TITLE
Feature/pljones audio stream saving

### PR DESCRIPTION
**Pull request by pljones**
* Initial .gitignore 
Administrative

* Fix up warning message
* Not all Windows file systems are case insensitive 
Bugfixes

* (Qt5) Use QCoreApplication for headless
Possible solution to get the application to run as a headless server but it loses the nice history graph, so not ideal.

* Avoid ESC closing chat
Because ESC shouldn't close the chat window.  Or the main app window.

* Add console logging support for Windows
Whilst looking for the headless support, I found this idea for Windows logging.  Again, it could possibly be improved (as it required extensive changes and isn't pretty).

* Add recording support with Reaper Project generation
The main feature!

   * **New *-r* option** to enable recording of PCM files and conversion to Reaper RPP with WAV files
   * **New *-R* option** to set the directory in which to create recording sessions
   You need to specify the *-R* option, there's no default... so I guess *-r* and *-R* could be combined.
   * **New *-T* option** to convert a session directory with PCM files into a Reaper RPP with WAV files
   You can use *-T* on "failed" sessions, if the -r option captures the PCMs but the RPP converter doesn't run for some reaon.  (It was useful during development, maybe less so once things seem stable.)

The recorder is implemented as a new thread with queuing from the main "real time" server thread.  Each frame of decompressed audio for each client is passed across and written out raw (i.e. LPCM).  Once all clients disconnect, the session is considered ended and the conversion from LPCM (BigEndian) to WAV (LittleEndian) happens, along with writing out the RPP file.

### CODE REVIEW

**Comment by pljones** [comment]
I noticed when testing that mono streams are not being handled correctly.  I've not checked where it's going wrong (could be anywhere from the `emit Frame(...)` to the `ReaperItem` writing itself).

**Comment by pljones** [comment]
OK, I'll let this version run for a while and see if it's doing the right thing.  Seemed okay when I switched from mono to stereo whilst connected (which I'd not tested properly before).

**Comment by pljones** [comment]
Hm.  I thought the change in how the PCM file was copied to the WAV file might speed things up significantly.  It didn't.

Plan B, then, is to write the headers with -1 sizes then come back later and update them with the correct numbers.  (That was the original design but I got lazy and initially just dumped the PCM data.... which lead to Plan A of converting that...)

**Comment by pljones** [comment]
>  But actually for the Chat dialog I find it convenient to close it with the ESC key. Why did you prevent it for the Chat dialog as well?

I'm a "vi" user.  I type "ESC" a lot (at the wrong time) after typing something in...  So it's really, really annoying to have a window that _isn't_ a dialog box closing when I press ESC.  Dialog boxes are the only windows that should respond to ESC (and should do so as if the Cancel button or equivalent, if there is one, were pressed).

**Comment by pljones** [comment]
> I would actually not change anything in the main.cpp to prevent a crash in Qt5. I would solve it where the crash happens -> in the logging graph C++ class.

I get a failure on start up, regardless of whether I requested the logging graph:
```
peter@nuc-peter:~/git/Jamulus$ ./Jamulus -s -n -y foo
- server mode chosen
- no GUI mode chosen
- history file name: foo
KiTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.
peter@nuc-peter:~/git/Jamulus$ ./Jamulus -s -n
- server mode chosen
- no GUI mode chosen
KiTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
qt.qpa.screen: QXcbConnection: Could not connect to display localhost:10.0
Could not connect to any X display.
peter@nuc-peter:~/git/Jamulus$
```

**Comment by corrados** [comment]
> I'm a "vi" user. I type "ESC" a lot (at the wrong time) after typing something in
Ok, I see. I am more a Windows user. So in your case it makes absolutely sense to prevent ESC to close the chat dialog :-).

**Comment by corrados** [comment]
> I get a failure on start up, regardless of whether I requested the logging graph:

That is interesting. It is a long time ago since I was looking at that issue. As far as I remember, I did not have such issues. Sometime soon (hopefully) I will have some time for Jamulus and will try to reproduce this issue on my PC.

**Pull request closed without merging**
